-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 01:12:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BookStoreCreator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BookStoreCreator` ;

-- -----------------------------------------------------
-- Schema BookStoreCreator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookStoreCreator` DEFAULT CHARACTER SET utf8 ;
USE `BookStoreCreator` ;

-- -----------------------------------------------------
-- Table `BookStoreCreator`.`authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookStoreCreator`.`authentication` ;

CREATE TABLE IF NOT EXISTS `BookStoreCreator`.`authentication` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStoreCreator`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookStoreCreator`.`inventory` ;

CREATE TABLE IF NOT EXISTS `BookStoreCreator`.`inventory` (
  `itemID` INT NOT NULL,
  `itemname` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStoreCreator`.`sold`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BookStoreCreator`.`sold` ;

CREATE TABLE IF NOT EXISTS `BookStoreCreator`.`sold` (
  `itemID` INT NOT NULL,
  `itemname` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
